BEGIN;

DROP TABLE IF EXISTS "transaction", "localisation", "bien" CASCADE;

CREATE TABLE bien (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
);

CREATE TABLE localisation (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
);

CREATE TABLE transaction (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
);

COMMIT;